name: Deploy Production Demo

on:
  push:
    branches:
       - main

jobs:
  deploy:
    name: Deploy WordPress Plugin via FTP
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: http://customer-support-bot.nichesite.org
    steps:

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ftpupload.net  
          username: ${{ secrets.FTP_USERNAME }} 
          password: ${{ secrets.FTP_PASSWORD }}  
          local-dir: ./  
          server-dir: /customer-support-bot.nichesite.org/htdocs/wp-content/plugins/customer-support-bot/
